In [5]:
import numpy as np

In [110]:
def zScoreScale(x, y):
    data = np.c_[x,y]
    mean = data.mean()
    sig = np.sqrt(((data - mean)**2).sum())
    scaled_x = np.zeros(x.shape)
    
    scaled_data = (data - mean)/sig
    scaled_y = (scaled_data[:,len(scaled_data[0])-1]).reshape(-1,1)
    for i in range(x.shape[1]):
        scaled_x[:,i] = scaled_data[:,i]
    return scaled_x, scaled_y, mean, sig

def zScoreDescale(x, y, mean, sig):
    scaled_data = np.c_[x,y]
    descaled_data = scaled_data * sig + mean
    
    descaled_x = np.zeros(x.shape)
    descaled_y = (descaled_data[:,len(descaled_data[0])-1]).reshape(-1,1)
    for i in range(x.shape[1]):
        descaled_x[:,i] = descaled_data[:,i]
        
    return descaled_x, descaled_y, mean, sig

In [153]:
def minMaxScale(x, y):
    data = np.c_[x, y]
    min_value = np.min(data)
    max_value = np.max(data)
    normalized_x = (x - min_value)/(max_value - min_value)
    normalized_y = (y - min_value)/(max_value - min_value)
    
    return normalized_x, normalized_y, min_value, max_value

def minMaxDescale(normalized_x,normalized_y,min_value,max_value):
    
    denormalized_x = (normalized_x * (max_value - min_value)) + min_value
    denormalized_y = (normalized_y * (max_value - min_value)) + min_value
    
    return denormalized_x, denormalized_y

In [161]:
def addPolynomialColumns(x, grau = 2):
    if grau < 2:
        return x
    novo_x = x.copy()
    for g in range(2 , grau + 1):
        for coluna in range(x.shape[1]):
            nova_coluna = x[:,coluna] ** g
            novo_x = np.c_[novo_x, nova_coluna]
    return novo_x

In [138]:
def GD(x, y, alpha = 0.1, lamb = 0, max_iterations = 10):
    
    n = len(y)
    x = np.c_[np.ones(n), x]
    w = np.zeros(x.shape[1]).reshape(-1,1)
    yhat = np.zeros(n).reshape(-1,1)
    e = np.zeros(n).reshape(-1,1)
                 
    for t in range(max_iterations):
        yhat = x @ w
        e = y - yhat
        w[0] = w[0] + (alpha/n * e.sum())
        for column in range(1, len(w)):
            w[column] = w[column] + alpha * ((e * x[:,[column]]).sum()/n - lamb * w[column])
                
    MSE = ((e ** 2).sum())/(2*n)
    return w, MSE
    

In [99]:
def SGD(x, y, alpha = 0.1, lamb = 0, max_iterations = 10):
    
    n = len(y)
    x = np.c_[np.ones(n), x]
    w = np.zeros(len(x[0]))
    yhat = np.zeros(n)
    e = np.zeros(n)
    indices = np.arange(n)
                 
    for t in range(max_iterations):
        np.random.shuffle(indices)
        for j in indices:
            yhat[j] = (x[j] * w).sum()
            e[j] = y[j] - yhat[j]
            w[0] = w[0] + (alpha * e[j]/n)
            for column in range(1, len(w)):
                w[column] = w[column] + alpha * ((e[j] * x[j,column]).sum()/n - lamb * w[column])
        #print("t = ", t)
        #print("yhat = ", yhat)
        #print("e = ", e)
        #print("w = ", w, "\n")
        
    MSE = ((e ** 2).sum())/(2*n)
    return w, MSE

In [3]:
def OLS(x, y, alpha = 0.1, l2 = 0):
    
    n = len(y)
    x = np.c_[np.ones(n), x]
    identity = np.identity(len(x[0]))
    w = np.linalg.solve((x.T @ x + l2 * identity),(x.T @ y)).reshape(-1,1)
    yhat = x @ w
    e = y - yhat
    MSE = ((e ** 2).sum())/(2*n)
    return w, MSE

In [160]:
x = np.array([1, 2, 3, 4]).reshape(-1,1)
y = np.array([3, 5, 7, 9]).reshape(-1,1)
print(x)
print(y)

#polynomialGD(x, y, max_iterations=10)

#normalized_x,normalized_y,min_value,max_value = minMaxScale(x, y)
#minMaxDescale(normalized_x,normalized_y,min_value,max_value)

addPolynomialColumns(x)

[[1]
 [2]
 [3]
 [4]]
[[3]
 [5]
 [7]
 [9]]


array([[ 1,  1],
       [ 2,  4],
       [ 3,  9],
       [ 4, 16]])